services:
  db:
    image: ${DB_IMAGE:?}
    env_file: ${ENV_FILE}
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  auth:
    image: ${AUTH_IMAGE:?}
    env_file: ${ENV_FILE}
    depends_on:
      - db

  rest:
    image: ${REST_IMAGE:?}
    env_file: ${ENV_FILE}
    environment:
      PGRST_DB_URI: postgres://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE}
    depends_on:
      - db

  realtime:
    image: ${REALTIME_IMAGE:?}
    env_file: ${ENV_FILE}
    depends_on:
      - db

  storage-api:
    image: ${STORAGE_IMAGE:?}
    env_file: ${ENV_FILE}
    depends_on:
      - db

  imgproxy:
    image: ${IMGPROXY_IMAGE:?}
    env_file: ${ENV_FILE}

  vector:
    image: ${VECTOR_IMAGE:?}
    env_file: ${ENV_FILE}
    depends_on:
      - db

  edge-runtime:
    image: ${EDGE_IMAGE:?}
    env_file: ${ENV_FILE}
    environment:
      SUPABASE_URL: http://kong:${KONG_HTTP_PORT}
      SUPABASE_ANON_KEY: ${ANON_KEY}
    volumes:
      - ../supabase/functions:/home/deno/functions:ro
      - ${EDGE_ENV_FILE}:/home/deno/.env:ro
    ports:
      - "${EDGE_PORT}:9000"
    depends_on:
      - db
      - auth
      - rest

  kong:
    image: ${KONG_IMAGE:?}
    env_file: ${ENV_FILE}
    ports:
      - "${KONG_HTTP_PORT}:8000"

volumes:
  db-data:
    name: supa-${VOL_NS}-db
