services:
  db:
    image: supabase/postgres:15.8.1.135
    restart: unless-stopped
    env_file: ${ENV_FILE}
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGHOST_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  auth:
    image: supabase/gotrue:v2.180.0
    restart: unless-stopped
    env_file: ${ENV_FILE}
    depends_on:
      - db

  rest:
    image: postgrest/postgrest:v13.0.7
    restart: unless-stopped
    env_file: ${ENV_FILE}
    environment:
      PGRST_DB_URI: postgres://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE}
    depends_on:
      - db

  realtime:
    image: supabase/realtime:v2.56.0
    restart: unless-stopped
    env_file: ${ENV_FILE}
    depends_on:
      - db

  storage-api:
    image: supabase/storage-api:v1.28.1
    restart: unless-stopped
    env_file: ${ENV_FILE}
    depends_on:
      - db

  imgproxy:
    image: darthsim/imgproxy:v3.8.0
    restart: unless-stopped
    env_file: ${ENV_FILE}

  edge-runtime:
    image: supabase/edge-runtime:v1.69.14
    restart: unless-stopped
    env_file: ${ENV_FILE}
    environment:
      SUPABASE_URL: http://kong:${KONG_HTTP_PORT}
      SUPABASE_ANON_KEY: ${ANON_KEY}
    volumes:
      - ../supabase/functions:/home/deno/functions:ro
      - ${EDGE_ENV_FILE}:/home/deno/.env:ro
    ports:
      - "${EDGE_PORT}:9000"
    depends_on:
      - db
      - auth
      - rest

  kong:
    image: kong:2.8.1
    restart: unless-stopped
    env_file: ${ENV_FILE}
    ports:
      - "${KONG_HTTP_PORT}:8000"

volumes:
  db-data:
    name: supa-${VOL_NS}-db
